### ISSUE TITLE
Threads for pg7 strain relief are too small

### ISSUE THREAD

**Issue by Pneumanifest** [bigtreetech/H2-V2X#1]
the threads in this part are too small. the pg7 has an outer diameter of 12.5mm the threads in the design are maybe 12.3 this won't work. Was it planned to use a different strain relief part? if PG7 was intended could you update the part to have the correct threads? 
![image](https://github.com/user-attachments/assets/886c9c47-79b7-4a16-8ecc-1be41bd3e584)
![image](https://github.com/user-attachments/assets/8703be81-297b-4e2e-9f3c-5b3a7dd43f5e)

**Comment by Pneumanifest** [comment]
I've modified the part to fit the PG7, but I see that its marked as CC no derivative so I cannot post it. Would it be something you could get updated?

**Comment by TrevTrev84** [comment]
I can most definitely take care of that... I was interested in this
extruder when they first came out but ended up getting a Galileo 2 for
reliability sake... How well does it print??

**Comment by Pneumanifest** [comment]
I'm still in the process of getting it all set up. I had to wait for wires to come in. Hopefully I can get it installed this week. All my other extruders are H2s so I'm expecting great things. It's my first rapido2 though 🤞

**Comment by Pneumanifest** [comment]
> I can most definitely take care of that...

Are you the one that made the model? I have also noticed that the two holes used to mount the EBB36 are slightly too large for M3 screws that come with the EBB36 but they are too small for for heat inserts, so those need a little modifying too. I can easily make the mods but because of @bigtreetech marking all files in the repo as CC-BY-NC-ND-4.0 I cannot share modified files (the ND part forbids that.) It would be nice to get it fixed or let others share modified files. There are some already asking me for that.

**Comment by BTTJUSTIN** [comment]
The documentation has been updated. Thanks again for pointing out the issue.
